version: '3.8'

services:
  mahjong:
    image: mahjong
    restart: always
    environment:
      - VIRTUAL_HOST=mahjong4friends.com
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=mahjong4friends.com
      - LETSENCRYPT_EMAIL=support@mahjong4friends.com
    expose:
      - 8080
    deploy:
      resources:
        limits:
          memory: 300M

networks:
  default:
    external:
      name: nginx-proxy
