version: '3.8'

services:
  mahjong:
    image: mahjong
    restart: always
    environment:
      - VIRTUAL_HOST=mahjong4friends.com
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=mahjong4friends.com
      - LETSENCRYPT_EMAIL=support@mahjong4friends.com
    expose:
      - 8080
    deploy:
      resources:
        limits:
          memory: 500M


  www-redirect:
    image: schmunk42/nginx-redirect
    container_name: mahjong-www-redirect
    environment:
      - VIRTUAL_HOST=www.mahjong4friends.com
      - LETSENCRYPT_HOST=www.mahjong4friends.com
      - LETSENCRYPT_EMAIL=support@mahjong4friends.com
      - SERVER_REDIRECT=mahjong4friends.com
      - SERVER_REDIRECT_SCHEME=https

networks:
  default:
    external:
      name: nginx-proxy
